# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task6UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from classes import CustomScrollArea, MousePad
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from matplotlib.patches import Circle
import numpy as np
from scipy import signal
from PyQt5.QtGui import QDoubleValidator
from PyQt5.QtCore import QLocale

class CustomizedFigureCanvas(FigureCanvas):
        def __init__(self, a_value):
                self.a_value = a_value
                fig = Figure()
                self.axes1 = fig.add_subplot(121)
                self.axes1.set_xlabel('Frequency(Hz)', fontsize=8)
                self.axes1.set_ylabel('Phase(rad)', fontsize=8)
                self.axes1.tick_params(axis='both', which='major', labelsize=5)
                self.axes1.xaxis.set_label_position('top')
                self.axes2 = fig.add_subplot(122)
                self.axes2.xaxis.set_label_position('top')
                self.axes2.yaxis.set_label_position('right')
                self.axes2.set_xlabel('Real', fontsize=8)
                self.axes2.set_ylabel('Imaginary', fontsize=8)
                self.axes2.grid(True)
                self.axes2.set_aspect('equal', 'box')
                self.axes2.set_xlim(-2.2, 2.2)
                self.axes2.set_ylim(-2.2, 2.2)
                self.axes2.tick_params(axis='both', which='major', labelsize=6)
                super(CustomizedFigureCanvas, self).__init__(fig)

                # draw unit circle in z-plane
                circle = Circle((0, 0), 1, color='k', fill=False)
                self.axes2.add_artist(circle)
                self.plotPhaseResponse(self.a_value)
                self.plotZeroesAndPoles(self.a_value)

        def plotPhaseResponse(self, a_value):
             num = [-np.conjugate(a_value), 1]
             den = [1, -a_value]
             w, response = signal.freqz(num, den)
             frequency = w/(2 * np.pi)
             phase = np.unwrap(np.angle(response))
             self.axes1.plot(frequency, phase)
        def plotZeroesAndPoles(self, a_value):
             a = a_value.real
             b = a_value.imag
             # plot the pole
             self.axes2.plot(a, b, "rx")
             zero = 1 / (np.conjugate(a_value))
             a = zero.real
             b = zero.imag
             # plot the zero
             self.axes2.plot(a, b, "bo")

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1414, 835)
        MainWindow.setMinimumSize(QtCore.QSize(1414, 835))
        MainWindow.setStyleSheet("/*QMainWindow{\n"
"    background-color: rgb(113, 127, 143);\n"
"}\n"
"/*-----------------------------------------------------------\n"
"QTabWidget{\n"
"    border: 2px solid black;\n"
"    border-radius: 7px;\n"
"}\n"
"/*-----------------------------------------------------------\n"
"QGroupBox{    \n"
"    background-color: rgb(165, 185, 208);\n"
"    border: 1px solid white;\n"
"    border-radius: 7px;\n"
"}\n"
"/*-----------------------------------------------------------\n"
"QPushButton{\n"
"    border: 2px solid white;\n"
"    border-radius: 7px;\n"
"}\n"
"/*-----------------------------------------------------------\n"
"QToolButton{\n"
"    border: 2px solid white;\n"
"    border-radius: 7px;\n"
"}\n"
"*/\n"
"\n"
"/* main */\n"
"QMainWindow {\n"
"    background-color: rgb(79, 90, 112);\n"
"}\n"
"QToolTip {\n"
"    color: black;\n"
"    background-color: white !important;\n"
"    border:none;\n"
"    /*border: 1px solid white;\n"
"    border-radius: 3px;*/\n"
"}\n"
"/* menubar */\n"
"QMenuBar {    \n"
"    font: 63 9pt \"Segoe UI Variable Text Semibold\";\n"
"    color: rgb(138, 138, 138);\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(207, 209, 207, 255), stop:1 rgba(230, 229, 230, 255));\n"
"}\n"
"QMenuBar::item:selected {\n"
"      background-color: rgb(161, 186, 230);\n"
"    color: #FFFFFF;\n"
"}\n"
"QMenu::item{    \n"
"    font: 8pt \"Segoe UI\";\n"
"}\n"
"QMenu::item:selected {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: rgb(161, 186, 230);\n"
"    border-bottom-color: transparent;\n"
"    border-left-width: 2px;\n"
"    color: #000000;\n"
"    padding-left:15px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    background-color: rgb(161, 186, 230);\n"
"}\n"
"QMenu::item {\n"
"    font: 8pt \"Segoe UI\";\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    color: #000000;\n"
"    padding-left:10px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"}\n"
"QGroupBox{    \n"
"    background-color: rgb(236, 236, 236);\n"
"    border: 2px solid rgb(190, 190, 190);\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollArea{    \n"
"    background-color: rgb(236, 236, 236);\n"
"    border: 4px solid rgb(190, 190, 190);\n"
"    border-radius: 7px;\n"
"}\n"
"QGraphicsView, QListView{    \n"
"    background-color: white;\n"
"    border: 2px solid rgb(190, 190, 190);\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"/* push button */\n"
"QPushButton, QToolButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(82, 94, 117);\n"
"    border: 1px solid rgb(82, 94, 117);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover, QToolButton:hover{\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(82, 94, 117);\n"
"    border-width: 2px;\n"
"    /*background-color: rgb(185, 222, 255);*/\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(161, 186, 230);\n"
"}\n"
"QPushButton:pressed, QToolButton:pressed{\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(138, 173, 204);\n"
"    border-width: 2px;\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgb(161, 186, 230);\n"
"}\n"
"/* slider */\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: rgb(82, 94, 117);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(79, 90, 112);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background-color: rgb(161, 186, 230);\n"
"}\n"
"/* LCD */\n"
"QLCDNumber {\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 14px;\n"
"    width: 14px;\n"
"    border-style:solid;\n"
"    border-radius:7px;\n"
"    border-width: 1px;\n"
"    border-color: rgb(79, 90, 112);\n"
"    background-color: rgb(161, 186, 230);\n"
"}\n"
"/* checkbox */\n"
"QCheckBox:hover {\n"
"    border-radius:2px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:2px;\n"
"    border-color: transparent;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    height: 11px;\n"
"    width: 11px;\n"
"    border-style:solid;\n"
"    border-radius: 2px;\n"
"    border-width: 1px;\n"
"    border-color: rgb(79, 90, 112);\n"
"    color: #000000;\n"
"    background-color: rgb(161, 186, 230);\n"
"\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    height: 11px;\n"
"    width: 11px;\n"
"    border-style:solid;\n"
"    border-radius: 2px;\n"
"    border-width: 1px;\n"
"    border-color: rgb(79, 90, 112);\n"
"    color: #000000;\n"
"}\n"
"/* combobox */\n"
"QComboBox{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(82, 94, 117);\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QComboBox::item{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(82, 94, 117);\n"
"    border-radius: 2px;\n"
"}\n"
"/* ListView */\n"
"QListView::item {\n"
"    text-align: center;\n"
"}\n"
"QListView::item:hover{\n"
"    border: 1px solid white;\n"
"    border-radius: 3px;\n"
"    background-color: rgb(181, 206, 250);\n"
"}\n"
"QListView::item:selected {\n"
"    border: 1px solid white;\n"
"    border-radius: 3px;\n"
"    background-color: rgb(240, 240, 240);\n"
"    color: rgb(140, 140, 140);\n"
"}\n"
"/* tab */\n"
"QTabWidget {\n"
"    border-radius: 6px;\n"
"    color:rgb(0,0,0);\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: rgb(223,223,223);\n"
"        background-color:rgb(226,226,226);\n"
"        border-style: solid;\n"
"        border-width: 2px;\n"
"        border-top-right-radius: 6px;\n"
"        border-bottom-right-radius: 6px;\n"
"        border-bottom-left-radius: 6px;\n"
"}\n"
"\n"
"QTabBar::tab:first {\n"
"      border-style: solid;\n"
"      border-right-width:1px;\n"
"    border-top-right-radius: 4px;\n"
"    border-top-left-radius: 4px;\n"
"    border-right-color: rgb(229, 229, 229);\n"
"    border-top-color: rgb(229, 229, 229);\n"
"    border-left-color: rgb(229, 229, 229);\n"
"    border-bottom-color: rgb(229, 229, 229);\n"
"    border-bottom-width: 0px;\n"
"    color: #ffffff;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: rgb(161, 186, 230);\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:first:selected{\n"
"    border-style: solid;\n"
"    border-left-width:1px;\n"
"    border-right-width:0px;\n"
"    border-top-width:1px;\n"
"    border-bottom-width:2px;\n"
"    border-top-color: rgb(229, 229, 229);\n"
"    border-left-color: rgb(229, 229, 229);\n"
"    border-bottom-color: rgb(82, 94, 117);\n"
"    /*border-top-left-radius: 4px;\n"
"    border-top-right-radius: 0px;*/\n"
"    color: #000000;\n"
"    padding: 1px;\n"
"    margin-left:0px;\n"
"    background-color:  rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:last {\n"
"      border-style: solid;\n"
"    border-top-right-radius: 4px;\n"
"    border-top-left-radius: 4px;\n"
"      border-left-width:1px;\n"
"      border-bottom-width:0px;\n"
"    border-right-color: rgb(229, 229, 229);\n"
"    border-top-color: rgb(229, 229, 229);\n"
"    border-left-color:rgb(229, 229, 229);\n"
"    border-bottom-color: rgb(229, 229, 229);\n"
"    color: #ffffff;\n"
"    padding: 1px;\n"
"    margin-left:0px;\n"
"    background-color: rgb(161, 186, 230);\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected{\n"
"    border-style: solid;\n"
"    border-left-width:0px;\n"
"    border-right-width:0px;\n"
"    border-top-width:0px;\n"
"    border-bottom-width:2px;\n"
"    border-top-color: rgb(82, 94, 117);\n"
"    border-left-color: rgb(82, 94, 117);\n"
"    border-bottom-color: rgb(82, 94, 117);\n"
"    /*border-top-left-radius: 0px;\n"
"    border-top-right-radius: 4px;*/\n"
"    color: #000000;\n"
"    padding: 1px;\n"
"    margin-left:0px;\n"
"    background-color:  rgb(255, 255, 255);\n"
"}\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"QTabBar::tab:hover{\n"
"    border-color: rgb(82, 94, 117);\n"
"    border-width: 2px;\n"
"    padding: 1px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_47 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.gridLayout_46 = QtWidgets.QGridLayout()
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setObjectName("gridLayout_24")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.toolButton_4 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_4.setEnabled(False)
        self.toolButton_4.setMinimumSize(QtCore.QSize(60, 60))
        self.toolButton_4.setStyleSheet("background-color: rgb(79, 90, 112);\n"
"border: none;")
        self.toolButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon)
        self.toolButton_4.setIconSize(QtCore.QSize(50, 50))
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout_18.addWidget(self.toolButton_4, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_18.addWidget(self.label, 0, 1, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_18, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_46.addLayout(self.gridLayout_24, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(1145, 635))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setContentsMargins(-1, 7, -1, -1)
        self.gridLayout_15.setVerticalSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border: 2px solid;\n"
"border-color:rgba(190, 190, 190,0);\n"
"border-bottom-color:rgb(190, 190, 190);\n"
"border-radius: 7px;\n"
"padding-bottom: 2px;")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_15.addWidget(self.label_16, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_41.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setContentsMargins(-1, 7, -1, 7)
        self.gridLayout_19.setVerticalSpacing(7)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setVerticalSpacing(10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setContentsMargins(-1, 0, -1, 5)
        self.gridLayout_12.setVerticalSpacing(15)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.checkBox_conjegates = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_conjegates.setMinimumSize(QtCore.QSize(0, 27))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_conjegates.setFont(font)
        self.checkBox_conjegates.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_conjegates.setObjectName("checkBox_conjegates")
        self.gridLayout_12.addWidget(self.checkBox_conjegates, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 1, 1, 1)
        self.pushButton_clear_all_z_p = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_clear_all_z_p.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_clear_all_z_p.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_clear_all_z_p.setFont(font)
        self.pushButton_clear_all_z_p.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_clear_all_z_p.setObjectName("pushButton_clear_all_z_p")
        self.gridLayout_3.addWidget(self.pushButton_clear_all_z_p, 0, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton_zeros = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_zeros.setMinimumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.toolButton_zeros.setFont(font)
        self.toolButton_zeros.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_zeros.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/zeros.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_zeros.setIcon(icon1)
        self.toolButton_zeros.setIconSize(QtCore.QSize(19, 19))
        self.toolButton_zeros.setObjectName("toolButton_zeros")
        self.gridLayout.addWidget(self.toolButton_zeros, 0, 0, 1, 1)
        self.toolButton_poles = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_poles.setMinimumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.toolButton_poles.setFont(font)
        self.toolButton_poles.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_poles.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/poles.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_poles.setIcon(icon2)
        self.toolButton_poles.setIconSize(QtCore.QSize(15, 16))
        self.toolButton_poles.setCheckable(False)
        self.toolButton_poles.setAutoRaise(False)
        self.toolButton_poles.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_poles.setObjectName("toolButton_poles")
        self.gridLayout.addWidget(self.toolButton_poles, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.pushButton_clear_z_p = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear_z_p.sizePolicy().hasHeightForWidth())
        self.pushButton_clear_z_p.setSizePolicy(sizePolicy)
        self.pushButton_clear_z_p.setMinimumSize(QtCore.QSize(70, 25))
        self.pushButton_clear_z_p.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_clear_z_p.setFont(font)
        self.pushButton_clear_z_p.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_clear_z_p.setObjectName("pushButton_clear_z_p")
        self.gridLayout_2.addWidget(self.pushButton_clear_z_p, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 1, 0, 1, 1)
        self.widget_unit_circle = QtWidgets.QWidget(self.groupBox)
        # self.widget_unit_circle = Z_plane(self.groupBox)
        self.widget_unit_circle.setMinimumSize(QtCore.QSize(225, 225))
        self.widget_unit_circle.setMaximumSize(QtCore.QSize(600, 400))
        self.widget_unit_circle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.widget_unit_circle.setStyleSheet("border: 2px solid rgb(190, 190, 190);\n"
"border-radius: 7px;\n"
"background-color: rgb(255, 255, 255);\n"
"padding: 3px;\n"
"")
        self.widget_unit_circle.setObjectName("widget_unit_circle")
        self.gridLayout_13.addWidget(self.widget_unit_circle, 0, 0, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setVerticalSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.plotWidget_mouse_movement = MousePad(self.groupBox)
        # self.plotWidget_mouse_movement = PlotWidget(self.groupBox)
        # self.plotWidget_mouse_movement.setBackground(mkColor((50, 50, 50)))
        # self.plotWidget_mouse_movement.hideAxis('bottom')
        # self.plotWidget_mouse_movement.hideAxis('left')
        self.plotWidget_mouse_movement.setMinimumSize(QtCore.QSize(270, 170))
        self.plotWidget_mouse_movement.setMaximumSize(QtCore.QSize(16777215, 300))
        self.plotWidget_mouse_movement.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.plotWidget_mouse_movement.setMouseTracking(False)
        self.plotWidget_mouse_movement.setStyleSheet("QWidget{\n"
"border: 3px solid rgb(190, 190, 190);\n"
"border-radius: 7px;\n"
"background-color: rgb(50, 50, 50);\n"
"}\n"
"QToolTip {\n"
"    color: black;\n"
"    background-color: white;\n"
"    border:none;\n"
"    /*border: 1px solid white;\n"
"    border-radius: 3px;*/\n"
"}")
        self.plotWidget_mouse_movement.setObjectName("plotWidget_mouse_movement")
        self.gridLayout_14.addWidget(self.plotWidget_mouse_movement, 2, 0, 1, 1)
        self.gridLayout_48 = QtWidgets.QGridLayout()
        self.gridLayout_48.setHorizontalSpacing(0)
        self.gridLayout_48.setObjectName("gridLayout_48")
        self.toolButton_5 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_5.setEnabled(False)
        self.toolButton_5.setMinimumSize(QtCore.QSize(50, 50))
        self.toolButton_5.setStyleSheet("background-color: rgba(79, 90, 112,0);\n"
"/*border:none;*/\n"
"border: 2px solid;\n"
"border-color:rgba(190, 190, 190,255);\n"
"border-radius: 7px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-left-radius: 0px;\n"
"border-left-width: 0px;\n"
"/*border-bottom-color:rgb(190, 190, 190);\n"
"border-bottom-right-radius: 4px;\n"
"border-bottom-left-radius: 0px;\n"
"margin-bottom: 3.4px;\n"
"margin-left: 0px;*/\n"
"padding: 0px;")
        self.toolButton_5.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/gesture_wrong.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("icons/gesture_wrong.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon3)
        self.toolButton_5.setIconSize(QtCore.QSize(55, 55))
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout_48.addWidget(self.toolButton_5, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 50))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border: 2px solid;\n"
"border-color:rgba(190, 190, 190,0);\n"
"border-bottom-color:rgb(190, 190, 190);\n"
"border-bottom-left-radius: 5px;\n"
"margin-right: 0px;")
        self.label_10.setScaledContents(False)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName("label_10")
        self.gridLayout_48.addWidget(self.label_10, 0, 0, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.groupBox)
        self.toolButton.setEnabled(False)
        self.toolButton.setMinimumSize(QtCore.QSize(50, 50))
        self.toolButton.setStyleSheet("background-color: rgba(79, 90, 112,0);\n"
"/*border:none;*/\n"
"border: 2px solid;\n"
"border-color:rgba(190, 190, 190,255);\n"
"border-radius: 7px;\n"
"border-bottom-left-radius: 0px;\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"border-right-width: 0px;\n"
"/*border-bottom-color:rgb(190, 190, 190);\n"
"border-bottom-right-radius: 4px;\n"
"border-bottom-left-radius: 0px;\n"
"margin-bottom: 3.4px;\n"
"margin-left: 0px;*/\n"
"padding: 0px;")
        self.toolButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/gesture_correct.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("icons/gesture_correct.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon4)
        self.toolButton.setIconSize(QtCore.QSize(55, 55))
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_48.addWidget(self.toolButton, 0, 1, 1, 1)
        self.gridLayout_48.setColumnStretch(0, 1)
        self.gridLayout_14.addLayout(self.gridLayout_48, 0, 0, 1, 1)
        self.gridLayout_14.setRowStretch(0, 1)
        self.gridLayout_14.setRowStretch(2, 2)
        self.gridLayout_19.addLayout(self.gridLayout_14, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_19.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout_19.setRowStretch(0, 2)
        self.gridLayout_41.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox, 1, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_15, 0, 0, 2, 1)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_16.addWidget(self.line, 0, 1, 2, 2)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: 2px solid;\n"
"border-color:rgba(190, 190, 190,0);\n"
"border-bottom-color:rgb(190, 190, 190);\n"
"border-radius: 7px;\n"
"padding-bottom: 2px;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.plotWidget_mag = PlotWidget(self.tab)
        self.plotWidget_mag.setBackground(mkColor('white'))
        self.plotWidget_mag.setMinimumSize(QtCore.QSize(390, 240))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.plotWidget_mag.setFont(font)
        self.plotWidget_mag.setStyleSheet("border: 2px solid rgb(190, 190, 190);\n"
"border-radius: 7px;\n"
"background-color: rgb(255, 255, 255);\n"
"padding: 1px;\n"
"\n"
"")
        self.plotWidget_mag.setObjectName("plotWidget_mag")
        self.gridLayout_4.addWidget(self.plotWidget_mag, 1, 0, 1, 1)
        self.gridLayout_4.setRowStretch(1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: 2px solid;\n"
"border-color:rgba(190, 190, 190,0);\n"
"border-bottom-color:rgb(190, 190, 190);\n"
"border-radius: 7px;\n"
"padding-bottom: 2px;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.plotWidget_phase = PlotWidget(self.tab)
        self.plotWidget_phase.setBackground(mkColor('white'))
        self.plotWidget_phase.setMinimumSize(QtCore.QSize(390, 240))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.plotWidget_phase.setFont(font)
        self.plotWidget_phase.setStyleSheet("border: 2px solid rgb(190, 190, 190);\n"
"border-radius: 7px;\n"
"background-color: rgb(255, 255, 255);\n"
"padding: 1px;")
        self.plotWidget_phase.setObjectName("plotWidget_phase")
        self.gridLayout_5.addWidget(self.plotWidget_phase, 1, 0, 1, 1)
        self.gridLayout_5.setRowStretch(1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_6 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border: 2px solid;\n"
"border-color:rgba(190, 190, 190,0);\n"
"border-bottom-color:rgb(190, 190, 190);\n"
"border-radius: 7px;\n"
"padding-bottom: 2px;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.plotWidget_real_time_signal = PlotWidget(self.tab)
        self.plotWidget_real_time_signal.setBackground(mkColor('white'))
        self.plotWidget_real_time_signal.setMinimumSize(QtCore.QSize(390, 240))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.plotWidget_real_time_signal.setFont(font)
        self.plotWidget_real_time_signal.setStyleSheet("border: 2px solid rgb(190, 190, 190);\n"
"border-radius: 7px;\n"
"background-color: rgb(255, 255, 255);\n"
"padding: 1px;")
        self.plotWidget_real_time_signal.setObjectName("plotWidget_real_time_signal")
        self.gridLayout_6.addWidget(self.plotWidget_real_time_signal, 1, 0, 1, 1)
        self.gridLayout_6.setRowStretch(1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setVerticalSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_7 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border: 2px solid;\n"
"border-color:rgba(190, 190, 190,0);\n"
"border-bottom-color:rgb(190, 190, 190);\n"
"border-radius: 7px;\n"
"padding-bottom: 2px;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 0, 0, 1, 1)
        self.plotWidget_filterred_signal = PlotWidget(self.tab)
        self.plotWidget_filterred_signal.setBackground(mkColor('white'))
        self.plotWidget_filterred_signal.setMinimumSize(QtCore.QSize(390, 240))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.plotWidget_filterred_signal.setFont(font)
        self.plotWidget_filterred_signal.setStyleSheet("border: 2px solid rgb(190, 190, 190);\n"
"border-radius: 7px;\n"
"background-color: rgb(255, 255, 255);\n"
"padding: 1px;")
        self.plotWidget_filterred_signal.setObjectName("plotWidget_filterred_signal")
        self.gridLayout_7.addWidget(self.plotWidget_filterred_signal, 1, 0, 1, 1)
        self.gridLayout_7.setRowStretch(1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_7, 1, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setHorizontalSpacing(7)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem4 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem5, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_10.addWidget(self.label_3, 0, 1, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setContentsMargins(15, -1, -1, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.horizontalSlider_filtration_speed = QtWidgets.QSlider(self.tab)
        self.horizontalSlider_filtration_speed.setMinimum(1)
        self.horizontalSlider_filtration_speed.setMaximum(100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_filtration_speed.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_filtration_speed.setSizePolicy(sizePolicy)
        self.horizontalSlider_filtration_speed.setMinimumSize(QtCore.QSize(370, 0))
        self.horizontalSlider_filtration_speed.setMaximumSize(QtCore.QSize(600, 16777215))
        self.horizontalSlider_filtration_speed.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_filtration_speed.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_filtration_speed.setObjectName("horizontalSlider_filtration_speed")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_filtration_speed)
        self.label_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.gridLayout_8.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.toolButton_filtration_start_stop = QtWidgets.QToolButton(self.tab)
        self.toolButton_filtration_start_stop.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.toolButton_filtration_start_stop.setFont(font)
        self.toolButton_filtration_start_stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_filtration_start_stop.setObjectName("toolButton_filtration_start_stop")
        self.gridLayout_8.addWidget(self.toolButton_filtration_start_stop, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_8, 0, 2, 1, 1)
        self.gridLayout_10.setColumnStretch(0, 1)
        self.gridLayout_10.setColumnStretch(3, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_11, 1, 2, 1, 1)
        self.gridLayout_16.setColumnStretch(0, 1)
        self.gridLayout_16.setColumnStretch(2, 3)
        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_43 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.gridLayout_42 = QtWidgets.QGridLayout()
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.gridLayout_39 = QtWidgets.QGridLayout()
        self.gridLayout_39.setVerticalSpacing(0)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("border: 2px solid;\n"
"border-color:rgba(190, 190, 190,0);\n"
"border-bottom-color:rgb(190, 190, 190);\n"
"border-radius: 4px;")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_39.addWidget(self.label_19, 0, 0, 1, 1)
        # self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea = CustomScrollArea(self.tab_2)
        self.scrollArea.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(True)
        self.scrollArea.setFont(font)
        self.scrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scrollArea.setAccessibleDescription("")
        self.scrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 392, 1128))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_45 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.gridLayout_44 = QtWidgets.QGridLayout()
        self.gridLayout_44.setObjectName("gridLayout_44")
        # self.graphicsView_7 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.graphicsView_7 = CustomizedFigureCanvas(complex(0.5))
        self.graphicsView_7.setMinimumSize(QtCore.QSize(200, 150))
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.gridLayout_44.addWidget(self.graphicsView_7, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_44.addWidget(self.label_25, 0, 1, 1, 1)
        self.gridLayout_45.addLayout(self.gridLayout_44, 0, 0, 1, 1)
        self.gridLayout_35 = QtWidgets.QGridLayout()
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.graphicsView_6 = CustomizedFigureCanvas(complex(-2+0.5*1j))
        self.graphicsView_6.setMinimumSize(QtCore.QSize(200, 150))
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.gridLayout_35.addWidget(self.graphicsView_6, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_35.addWidget(self.label_24, 0, 1, 1, 1)
        self.gridLayout_45.addLayout(self.gridLayout_35, 1, 0, 1, 1)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.graphicsView = CustomizedFigureCanvas(complex(-0.7))
        self.graphicsView.setMinimumSize(QtCore.QSize(200, 150))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_20.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_20.addWidget(self.label_18, 0, 1, 1, 1)
        self.gridLayout_45.addLayout(self.gridLayout_20, 2, 0, 1, 1)
        self.gridLayout_31 = QtWidgets.QGridLayout()
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_31.addWidget(self.label_21, 0, 1, 1, 1)
        self.graphicsView_5 = CustomizedFigureCanvas(complex(1+2*1j))
        self.graphicsView_5.setMinimumSize(QtCore.QSize(200, 150))
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.gridLayout_31.addWidget(self.graphicsView_5, 0, 0, 1, 1)
        self.gridLayout_45.addLayout(self.gridLayout_31, 3, 0, 1, 1)
        self.gridLayout_32 = QtWidgets.QGridLayout()
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.graphicsView_2 = CustomizedFigureCanvas(complex(-0.9*1j))
        self.graphicsView_2.setMinimumSize(QtCore.QSize(200, 150))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_32.addWidget(self.graphicsView_2, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_32.addWidget(self.label_22, 0, 1, 1, 1)
        self.gridLayout_45.addLayout(self.gridLayout_32, 4, 0, 1, 1)
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.graphicsView_4 = CustomizedFigureCanvas(complex(1.5-0.6*1j))
        self.graphicsView_4.setMinimumSize(QtCore.QSize(200, 150))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.gridLayout_33.addWidget(self.graphicsView_4, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_33.addWidget(self.label_15, 0, 1, 1, 1)
        self.gridLayout_45.addLayout(self.gridLayout_33, 5, 0, 1, 1)
        self.gridLayout_34 = QtWidgets.QGridLayout()
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.graphicsView_3 = CustomizedFigureCanvas(0.8)
        self.graphicsView_3.setMinimumSize(QtCore.QSize(200, 150))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.gridLayout_34.addWidget(self.graphicsView_3, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_34.addWidget(self.label_20, 0, 1, 1, 1)
        self.gridLayout_45.addLayout(self.gridLayout_34, 6, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_39.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.gridLayout_42.addLayout(self.gridLayout_39, 0, 0, 1, 1)
        self.gridLayout_40 = QtWidgets.QGridLayout()
        self.gridLayout_40.setVerticalSpacing(0)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("border: 2px solid;\n"
"border-color:rgba(190, 190, 190,0);\n"
"border-bottom-color:rgb(190, 190, 190);\n"
"border-radius: 4px;")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_40.addWidget(self.label_23, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_38.setContentsMargins(-1, 7, -1, -1)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.gridLayout_37 = QtWidgets.QGridLayout()
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setVerticalSpacing(0)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("border: 2px solid;\n"
"border-color:rgba(190, 190, 190,0);\n"
"border-bottom-color:rgb(190, 190, 190);\n"
"border-radius: 4px;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_25.addWidget(self.label_14, 0, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 350))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.listWidget.setFont(font)
        self.listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget.setStyleSheet("")
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.listWidget.setProperty("showDropIndicator", False)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setMovement(QtWidgets.QListView.Static)
        self.listWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setSelectionRectVisible(False)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_25.addWidget(self.listWidget, 1, 0, 1, 1)
        self.gridLayout_25.setRowStretch(1, 1)
        self.gridLayout_30.addLayout(self.gridLayout_25, 0, 0, 1, 1)
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setObjectName("gridLayout_29")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_29.addItem(spacerItem6, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_29.addItem(spacerItem7, 0, 2, 1, 1)
        self.pushButton_clear_all_pass_filters = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear_all_pass_filters.sizePolicy().hasHeightForWidth())
        self.pushButton_clear_all_pass_filters.setSizePolicy(sizePolicy)
        self.pushButton_clear_all_pass_filters.setMinimumSize(QtCore.QSize(70, 25))
        self.pushButton_clear_all_pass_filters.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_clear_all_pass_filters.setFont(font)
        self.pushButton_clear_all_pass_filters.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_clear_all_pass_filters.setObjectName("pushButton_clear_all_pass_filters")
        self.gridLayout_29.addWidget(self.pushButton_clear_all_pass_filters, 0, 1, 1, 1)
        self.gridLayout_29.setColumnStretch(1, 1)
        self.gridLayout_30.addLayout(self.gridLayout_29, 1, 0, 1, 1)
        self.gridLayout_30.setRowStretch(0, 1)
        self.gridLayout_37.addLayout(self.gridLayout_30, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 169, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_37.addItem(spacerItem8, 1, 0, 1, 1)
        self.gridLayout_36 = QtWidgets.QGridLayout()
        self.gridLayout_36.setVerticalSpacing(15)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border: 2px solid;\n"
"border-color:rgba(190, 190, 190,0);\n"
"border-bottom-color:rgb(190, 190, 190);\n"
"border-radius: 7px;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_36.addWidget(self.label_11, 0, 0, 1, 1)
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setObjectName("gridLayout_28")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem9, 0, 0, 1, 1)
        self.gridLayout_26 = QtWidgets.QGridLayout()
        self.gridLayout_26.setHorizontalSpacing(3)
        self.gridLayout_26.setVerticalSpacing(7)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_26.addWidget(self.label_12, 0, 2, 1, 1)
        self.lineEdit_real = QtWidgets.QLineEdit(self.groupBox_2)
        # validator = QDoubleValidator(0, 1, 2)
        # validator.setLocale(QLocale(QLocale.C)) # Set the locale to C
        # self.lineEdit_real.setValidator(validator)
        self.lineEdit_real.setMinimumSize(QtCore.QSize(40, 35))
        self.lineEdit_real.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_real.setSizeIncrement(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.lineEdit_real.setFont(font)
        self.lineEdit_real.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(190, 190, 190);\n"
"border-radius: 7px;\n"
"")
        self.lineEdit_real.setMaxLength(4)
        self.lineEdit_real.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_real.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_real.setPlaceholderText("")
        self.lineEdit_real.setObjectName("lineEdit_real")
        self.gridLayout_26.addWidget(self.lineEdit_real, 0, 1, 1, 1)
        self.lineEdit_imaginary = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_imaginary.setMinimumSize(QtCore.QSize(40, 35))
        self.lineEdit_imaginary.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_imaginary.setSizeIncrement(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.lineEdit_imaginary.setFont(font)
        self.lineEdit_imaginary.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(190, 190, 190);\n"
"border-radius: 7px;\n"
"")
        self.lineEdit_imaginary.setMaxLength(4)
        self.lineEdit_imaginary.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_imaginary.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_imaginary.setPlaceholderText("")
        self.lineEdit_imaginary.setObjectName("lineEdit_imaginary")
        self.gridLayout_26.addWidget(self.lineEdit_imaginary, 0, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_26.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setMinimumSize(QtCore.QSize(10, 35))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_26.addWidget(self.label_13, 0, 4, 1, 1)
        self.gridLayout_28.addLayout(self.gridLayout_26, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem10, 0, 2, 1, 1)
        self.gridLayout_36.addLayout(self.gridLayout_28, 1, 0, 1, 1)
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem11, 0, 2, 1, 1)
        self.pushButton_save_customized_filter = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save_customized_filter.sizePolicy().hasHeightForWidth())
        self.pushButton_save_customized_filter.setSizePolicy(sizePolicy)
        self.pushButton_save_customized_filter.setMinimumSize(QtCore.QSize(70, 25))
        self.pushButton_save_customized_filter.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_save_customized_filter.setFont(font)
        self.pushButton_save_customized_filter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_save_customized_filter.setObjectName("pushButton_save_customized_filter")
        self.gridLayout_27.addWidget(self.pushButton_save_customized_filter, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem12, 0, 0, 1, 1)
        self.gridLayout_27.setColumnStretch(1, 1)
        self.gridLayout_36.addLayout(self.gridLayout_27, 2, 0, 1, 1)
        self.gridLayout_37.addLayout(self.gridLayout_36, 2, 0, 1, 1)
        self.gridLayout_37.setRowStretch(0, 2)
        self.gridLayout_37.setRowStretch(1, 1)
        self.gridLayout_37.setRowStretch(2, 1)
        self.gridLayout_38.addLayout(self.gridLayout_37, 0, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_38.addItem(spacerItem13, 1, 0, 1, 1)
        self.gridLayout_40.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.gridLayout_42.addLayout(self.gridLayout_40, 0, 1, 1, 1)
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setVerticalSpacing(0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border: 2px solid;\n"
"border-color:rgba(190, 190, 190,0);\n"
"border-bottom-color:rgb(190, 190, 190);\n"
"border-radius: 7px;\n"
"padding-bottom: 2px;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_21.addWidget(self.label_9, 0, 0, 1, 1)
        self.plotWidget_all_pass_filter = PlotWidget(self.tab_2)
        self.plotWidget_all_pass_filter.setLabel('left', 'Phase (rad)')
        self.plotWidget_all_pass_filter.setLabel('bottom', 'Frequency (Hz)')
        self.plotWidget_all_pass_filter.setBackground(mkColor('white'))
        self.plotWidget_all_pass_filter.setMinimumSize(QtCore.QSize(390, 240))
        self.plotWidget_all_pass_filter.setMaximumSize(QtCore.QSize(940, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.plotWidget_all_pass_filter.setFont(font)
        self.plotWidget_all_pass_filter.setStyleSheet("border: 2px solid rgb(190,190,190);\n"
"border-radius: 7px;\n"
"background-color: rgb(255, 255, 255);\n"
"padding: 1px;")
        self.plotWidget_all_pass_filter.setObjectName("plotWidget_all_pass_filter")
        self.gridLayout_21.addWidget(self.plotWidget_all_pass_filter, 1, 0, 1, 1)
        self.gridLayout_21.setRowStretch(1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_21, 1, 0, 1, 1)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setVerticalSpacing(0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border: 2px solid;\n"
"border-color:rgba(190, 190, 190,0);\n"
"border-bottom-color:rgb(190, 190, 190);\n"
"border-radius: 7px;\n"
"padding-bottom: 2px;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_22.addWidget(self.label_8, 0, 0, 1, 1)
        self.plotWidget_filterred_phase = PlotWidget(self.tab_2)
        self.plotWidget_filterred_phase.setBackground(mkColor('white'))
        self.plotWidget_filterred_phase.setMinimumSize(QtCore.QSize(390, 240))
        self.plotWidget_filterred_phase.setMaximumSize(QtCore.QSize(940, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.plotWidget_filterred_phase.setFont(font)
        self.plotWidget_filterred_phase.setStyleSheet("border: 2px solid rgb(190,190,190);\n"
"border-radius: 7px;\n"
"background-color: rgb(255, 255, 255);\n"
"padding: 1px;")
        self.plotWidget_filterred_phase.setObjectName("plotWidget_filterred_phase")
        self.gridLayout_22.addWidget(self.plotWidget_filterred_phase, 1, 0, 1, 1)
        self.gridLayout_22.setRowStretch(1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_22, 0, 0, 1, 1)
        self.gridLayout_42.addLayout(self.gridLayout_23, 0, 2, 1, 1)
        self.gridLayout_42.setColumnStretch(0, 1)
        self.gridLayout_42.setColumnStretch(1, 1)
        self.gridLayout_42.setColumnStretch(2, 2)
        self.gridLayout_43.addLayout(self.gridLayout_42, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_46.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout_47.addLayout(self.gridLayout_46, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1414, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Digital Filter Designer"))
        self.label_16.setText(_translate("MainWindow", "Desining Tools"))
        self.checkBox_conjegates.setText(_translate("MainWindow", "Conjegates"))
        self.pushButton_clear_all_z_p.setToolTip(_translate("MainWindow", "Clear all zeros and all poles"))
        self.pushButton_clear_all_z_p.setText(_translate("MainWindow", "CLear All"))
        self.toolButton_zeros.setToolTip(_translate("MainWindow", "Add zeros"))
        self.toolButton_poles.setToolTip(_translate("MainWindow", "Add poles"))
        self.pushButton_clear_z_p.setToolTip(_translate("MainWindow", "Clear all zeros/poles"))
        self.pushButton_clear_z_p.setText(_translate("MainWindow", "Clear"))
        self.plotWidget_mouse_movement.setToolTip(_translate("MainWindow", "Move the mouse vertically to create a real-time signal"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>Speed-Frequency Signal Synthesizer</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Magnitude Response"))
        self.label_5.setText(_translate("MainWindow", "Phase Response"))
        self.label_6.setText(_translate("MainWindow", "Real-Time Original Signal"))
        self.label_7.setText(_translate("MainWindow", "Real-Time Filterred Signal"))
        self.label_3.setText(_translate("MainWindow", "Filtration"))
        self.label_2.setText(_translate("MainWindow", "Speed"))
        self.toolButton_filtration_start_stop.setText(_translate("MainWindow", "Stop/Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Filter Design"))
        self.label_19.setText(_translate("MainWindow", "Filters Library"))
        self.label_25.setText(_translate("MainWindow", "a=0.5 "))
        self.label_24.setText(_translate("MainWindow", "a=-2+0.5j "))
        self.label_18.setText(_translate("MainWindow", "a=-0.7 "))
        self.label_21.setText(_translate("MainWindow", "a=1+2j "))
        self.label_22.setText(_translate("MainWindow", "a=-0.9j "))
        self.label_15.setText(_translate("MainWindow", "a=1.5-0.6j "))
        self.label_20.setText(_translate("MainWindow", "a=0.8 "))
        self.label_23.setText(_translate("MainWindow", "Designing Tools"))
        self.label_14.setText(_translate("MainWindow", "Added Filters"))
        self.pushButton_clear_all_pass_filters.setText(_translate("MainWindow", "Clear"))
        self.label_11.setText(_translate("MainWindow", "Customize"))
        self.label_12.setText(_translate("MainWindow", "+"))
        self.label_17.setText(_translate("MainWindow", "a = "))
        self.label_13.setText(_translate("MainWindow", "i "))
        self.pushButton_save_customized_filter.setText(_translate("MainWindow", "Save"))
        self.label_9.setText(_translate("MainWindow", "All-Pass Filter"))
        self.label_8.setText(_translate("MainWindow", "Phase Response"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "All-Pass Filters"))
from pyqtgraph import PlotWidget, mkColor

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
